on:
  workflow_dispatch:
    inputs:
      linux:
        description: "Run linux build?"
        required: true
        type: boolean
      windows:
          description: "Run windows build?"
          required: true
          type: boolean
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    if: ${{ inputs.linux || inputs.linux == null }}
    uses: feraxhp/ship-rs/.github/workflows/linux.yml@v0.2.0
    permissions:
      contents: write
    with:
      binary: cim

  build-windows:
    if: ${{ inputs.windows || inputs.windows == null }}
    permissions:
        contents: write
    name: 💻 Windows Build
    uses: ./.github/workflows/windows.yml

  publish-winget:
    if: ${{ inputs.windows || inputs.windows == null }}
    permissions:
      contents: read
    name: 🔥 Publish on windows
    needs: build-windows
    uses: ./.github/workflows/winget.yml
    secrets:
      TOKEN: ${{ secrets.TOKEN }}